services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:8-alpine
    restart: always
    networks:
      - app-network
    tmpfs:
      - /data

networks:
  app-network:
    driver: bridge